routes/web.php
<?php

use App\Http\Controllers\admin\Auth\LoginController;
use App\Http\Controllers\admin\SubscriptionPlanController;
use App\Http\Controllers\admin\TemplateController;
use App\Http\Controllers\admin\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([
    'prefix' => 'portal',
    'as' => 'portal.',
    'middleware' => 'web'
], function() {
    Route::get('/', function() {
        return view('portal.pages.home.index');
    })->name('home');
});

Route::group([
    'prefix' => 'admin',
    'as' => 'admin.',
    'middleware' => ['web']
], function() {
    // Auth Routes
    Route::get('/login', [LoginController::class, 'showLoginForm'])->name('login');
    Route::post('/login', [LoginController::class, 'login'])->name('login.action');
    Route::post('/logout', [LoginController::class, 'logout'])->name('logout');

    // Must 'Auth' Routes
    Route::group([
        'middleware' => ['auth']
    ], function() {
        // Dashboard routes
        Route::get('/dashboard', function() {
            return view('admin.pages.dashboard.index');
        })->name('dashboard');

        // User's Routes
        Route::get('/users', [UserController::class, 'index'])->name('users');
        Route::get('/users/create', [UserController::class, 'create'])->name('users.create');
        Route::post('/users/create', [UserController::class, 'store'])->name('users.store');
        Route::get('/users/{id}/edit', [UserController::class, 'edit'])->name('users.edit');
        Route::post('/users/{id}/edit', [UserController::class, 'update'])->name('users.update');
        Route::delete('/users/{id}/delete', [UserController::class, 'destroy'])->name('users.delete');

        // Template's Routes
        Route::get('/templates', [TemplateController::class, 'index'])->name('templates');
        Route::get('/templates/create', [TemplateController::class, 'create'])->name('templates.create');
        Route::post('/templates/create', [TemplateController::class, 'store'])->name('templates.store');
        Route::get('/templates/{id}/edit', [TemplateController::class, 'edit'])->name('templates.edit');
        Route::post('/templates/{id}/edit', [TemplateController::class, 'update'])->name('templates.update');
        Route::delete('/templates/{id}/delete', [TemplateController::class, 'destroy'])->name('templates.delete');

        // Subscription Plan's Routes
        Route::get('/subscription_plan', [SubscriptionPlanController::class, 'index'])->name('subscription_plan');
        Route::get('/subscription_plan/create', [SubscriptionPlanController::class, 'create'])->name('subscription_plan.create');
        Route::post('/subscription_plan/create', [SubscriptionPlanController::class, 'store'])->name('subscription_plan.store');
        Route::get('/subscription_plan/{id}/edit', [SubscriptionPlanController::class, 'edit'])->name('subscription_plan.edit');
        Route::post('/subscription_plan/{id}/edit', [SubscriptionPlanController::class, 'update'])->name('subscription_plan.update');
        Route::delete('/subscription_plan/{id}/delete', [SubscriptionPlanController::class, 'destroy'])->name('subscription_plan.delete');
    });
});

Route::get('/admin', function() {
    return redirect('/admin/dashboard');
});

Route::get('/', function () {
    return view('portal.pages.home.index');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/SubscriptionPlan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class SubscriptionPlan extends Model
{
    use HasFactory, SoftDeletes;

    protected $table = 'subscription_plans';
    protected $guarded = [
        'id'
    ];
}

app/Http/Controllers/admin/SubscriptionPlanController.php
<?php

namespace App\Http\Controllers\admin;

use App\Helpers\Helper;
use App\Http\Controllers\Controller;
use App\Src\Actions\admin\SubscriptionPlan\{GetSubscriptionIndexAction, GetSubscriptionByIdAction, StoreSubscriptionAction, UpdateSubscriptionAction, DeleteSubscriptionAction};
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class SubscriptionPlanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        try {
            $subscriptions = (new GetSubscriptionIndexAction($request->all()))->execute();

            return view('admin.pages.subscription_plan.index', [
                'subscriptions' => $subscriptions,
            ]);
        } catch(\Exception $e) {
            return $e->getMessage();
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.pages.subscription_plan.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'price' => 'required|numeric',
            'benefit' => 'required',
            'duration' => 'required|numeric|min:1'
        ]);

        if($validator->fails()) {
            return response()->json([
                'status' => 'failed',
                'type' => 'validate',
                'error' => ucwords(implode(', ', $validator->errors()->all()))
            ]);
        }

        try {
            $user = (new StoreSubscriptionAction($request->all()))->execute();

            return Helper::jsonSuccessResponse('Subscription Plan created!', $user);
        } catch(\Exception $e) {
            return Helper::jsonFailedResponse('', $e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $subscription = (new GetSubscriptionByIdAction(decrypt($id)))->execute();

        return view('admin.pages.subscription_plan.edit', [
            'subscription' => $subscription
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'name' => 'required',
            'price' => 'required|numeric',
            'benefit' => 'required',
            'duration' => 'required|numeric|min:1'
        ]);

        if($validator->fails()) {
            return response()->json([
                'status' => 'failed',
                'type' => 'validate',
                'error' => ucwords(implode(', ', $validator->errors()->all()))
            ]);
        }

        try {
            $user = (new UpdateSubscriptionAction($request->all(), decrypt($id)))->execute();

            return Helper::jsonSuccessResponse('Subscription Plan created!', $user);
        } catch(\Exception $e) {
            return Helper::jsonFailedResponse('', $e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $subscription = (new DeleteSubscriptionAction(decrypt($id)))->execute();

            return Helper::jsonSuccessResponse('Subscription Plan deleted!', $subscription);
        } catch(\Exception $e) {
            return Helper::jsonFailedResponse('', $e->getMessage());
        }
    }
}

resources/views/admin/pages/subscription_plan/index.blade.php
@extends('admin.layouts.app')

@section('title', env('APP_NAME') . ' | Subscription Plans')

@section('content')
<div class="row page-titles mx-0">
    <div class="col p-md-0">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">Dashboard</li>
            <li class="breadcrumb-item active"><a href="{{ route('admin.dashboard') }}">Home</a></li>
        </ol>
    </div>
</div>
<div class="container-fluid mt-3">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        <h3 class="card-label">Subscription Plan Management</h3>
                    </div>
                </div>
                <div class="card-body">
                    <form action="" method="GET">
                        <div class="form-row">
                            <div class="form-group col-md-3">
                                <label>&nbsp;</label>
                                <a href="javascript:void(0)" data-href="{{ route('admin.subscription_plan.create') }}" class="btn btn-success btn-block btnAdd">
                                    <i class="icon-plus"></i> Create subscription
                                </a>
                            </div>
                            <div class="form-group col-md-3">
                                
                            </div>
                            <div class="form-group col-md-3">
                                <label>Search Field</label>
                                <input type="text" class="form-control input-default" name="search" id="search" value="{{ Request()->search }}" placeholder="Search by subscription's name or email">
                            </div>
                            <div class="form-group col-md-3">
                                <label>&nbsp;</label>
                                <button class="btn btn-primary btn-block" type="submit" href="{{ url()->current() }}?search={{ Request()->search }}">
                                    <i class="icon-magnifier"></i> Search
                                </button>
                            </div>
                        </div>
                    </form>
                    {{-- Table Index subscriptions --}}
                    <div class="table-responsive">
                        <table class="table table-striped table-hover" id="subscriptions-table">
                            <thead>
                                <tr>
                                    <td>#</td>
                                    <td>Name</td>
                                    <td>Price</td>
                                    <td>Benefit</td>
                                    <td>Duration</td>
                                    <td>Action</td>
                                </tr>
                            </thead>
                            <tbody>
                                @if(count($subscriptions) > 0)
                                    @foreach($subscriptions as $index => $subscription)
                                        <tr>
                                            <td>{!! ($index+1)+((Request::input('page') != 0 ? (Request::input('page')-1) : Request::input('page'))*1) !!}</td>
                                            <td>{{ $subscription->name }}</td>
                                            <td>{{ number_format($subscription->price) }}</td>
                                            <td>{{ $subscription->benefit }}</td>
                                            <td>{{ $subscription->duration }}</td>
                                            <td>
                                                <a href="javascript:void(0)" class="edit-data" data-href="{{ route('admin.subscription_plan.edit', encrypt($subscription->id)) }}" title="Edit subscription">
                                                    <i class="icon-note text-info"></i>
                                                </a>
                                                <a href="javascript:void(0)" class="delete-data" title="Delete subscription" data-href="{{ route('admin.subscription_plan.delete', encrypt($subscription->id)) }}">
                                                    <i class="icon-trash text-danger"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    @endforeach
                                @else
                                    <tr>
                                        <td colspan="6" style="text-align: center">
                                            <i>Data Not Found</i>
                                        </td>
                                    </tr>
                                @endif
                            </tbody>
                        </table>
                    </div>
                    {{-- End of Table Index subscriptions --}}
                </div>
                <div class="card-footer">
                    <div class="row">
                        <div class="col-md-5" style="float: left">
                            <small>Showing {{ $subscriptions->count() }} from {{ $subscriptions->total() }} data</small>
                        </div>
                        <div class="col-md-7">
                            <div style="float: right">
                                {!! $subscriptions->links() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- #/ container -->
@endsection

{{-- Styles Section --}}
@section('styles')
@endsection

{{-- Scripts Section --}}
@section('scripts')
<script>
    function deletesubscription(url)
    {
        $.ajax({
                url: url,
                type: 'DELETE',
                data: {
                    _token: '{{ csrf_token() }}'
                },
                success: function(response) {
                    if(response.status === 'success') {
                        swal({
                            title: 'Success!',
                            text: response.msg,
                            type: 'success',
                            showConfirmButton: false,
                            timer: 2000
                        }, () => {
                            window.location.reload();
                        })
                    } else {
                        swal({
                            title: response.msg,
                            text: response.error,
                            type: 'error',
                        })
                    }
                }
            })
    }

    $(document).ready(function() {
        $('.btnAdd').click(function(e) {
            e.preventDefault()
            swalLoading()
            $.ajax({
                url: $(this).attr('data-href'),
                type: 'GET',
                success: function(response) {
                    swal.close()
                    $.fancybox.open([
                        {
                            src: response,
                            type: 'html'
                        }
                    ])
                }
            })
        })

        $('.edit-data').on('click', function(e) {
            e.preventDefault()
            swalLoading()
            $.ajax({
                url: $(this).attr('data-href'),
                type: 'GET',
                success: function(response) {
                    swal.close()
                    $.fancybox.open([
                        {
                            src: response,
                            type: 'html'
                        }
                    ])
                }
            })
        })

        $('.delete-data').on('click', function(e) {
            e.preventDefault()
            let url = $(this).attr('data-href');
            swal({
                type: 'warning',
                title: 'Are you sure want to delete data?',
                text: 'Once deleted, data cannot be restore',
                showCancelButton: true
            }, (result) => {
                if(result) {
                    deletesubscription(url)
                }
            })
        })
    })
</script>
@endsection