routes/web.php
<?php

use App\Http\Controllers\admin\Auth\LoginController;
use App\Http\Controllers\admin\SubscriptionPlanController;
use App\Http\Controllers\admin\TemplateController;
use App\Http\Controllers\admin\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([
    'prefix' => 'portal',
    'as' => 'portal.',
    'middleware' => 'web'
], function() {
    Route::get('/', function() {
        return view('portal.pages.home.index');
    })->name('home');
});

Route::group([
    'prefix' => 'admin',
    'as' => 'admin.',
    'middleware' => ['web']
], function() {
    // Auth Routes
    Route::get('/login', [LoginController::class, 'showLoginForm'])->name('login');
    Route::post('/login', [LoginController::class, 'login'])->name('login.action');
    Route::post('/logout', [LoginController::class, 'logout'])->name('logout');

    // Must 'Auth' Routes
    Route::group([
        'middleware' => ['auth']
    ], function() {
        // Dashboard routes
        Route::get('/dashboard', function() {
            return view('admin.pages.dashboard.index');
        })->name('dashboard');

        // User's Routes
        Route::get('/users', [UserController::class, 'index'])->name('users');
        Route::get('/users/create', [UserController::class, 'create'])->name('users.create');
        Route::post('/users/create', [UserController::class, 'store'])->name('users.store');
        Route::get('/users/{id}/edit', [UserController::class, 'edit'])->name('users.edit');
        Route::post('/users/{id}/edit', [UserController::class, 'update'])->name('users.update');
        Route::delete('/users/{id}/delete', [UserController::class, 'destroy'])->name('users.delete');

        // Template's Routes
        Route::get('/templates', [TemplateController::class, 'index'])->name('templates');
        Route::get('/templates/create', [TemplateController::class, 'create'])->name('templates.create');
        Route::post('/templates/create', [TemplateController::class, 'store'])->name('templates.store');
        Route::get('/templates/{id}/edit', [TemplateController::class, 'edit'])->name('templates.edit');
        Route::post('/templates/{id}/edit', [TemplateController::class, 'update'])->name('templates.update');
        Route::delete('/templates/{id}/delete', [TemplateController::class, 'destroy'])->name('templates.delete');

        // Subscription Plan's Routes
        Route::get('/subscription_plan', [SubscriptionPlanController::class, 'index'])->name('subscription_plan');
        Route::get('/subscription_plan/create', [SubscriptionPlanController::class, 'create'])->name('subscription_plan.create');
        Route::post('/subscription_plan/create', [SubscriptionPlanController::class, 'store'])->name('subscription_plan.store');
        Route::get('/subscription_plan/{id}/edit', [SubscriptionPlanController::class, 'edit'])->name('subscription_plan.edit');
        Route::post('/subscription_plan/{id}/edit', [SubscriptionPlanController::class, 'update'])->name('subscription_plan.update');
        Route::delete('/subscription_plan/{id}/delete', [SubscriptionPlanController::class, 'destroy'])->name('subscription_plan.delete');
    });
});

Route::get('/admin', function() {
    return redirect('/admin/dashboard');
});

Route::get('/', function () {
    return view('portal.pages.home.index');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'role_id',
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function role(): BelongsTo
    {
        return $this->belongsTo(Role::class, 'role_id');
    }

    public function user_info(): HasOne
    {
        return $this->hasOne(UserDetails::class, 'user_id', 'id');
    }
}

app/Http/Controllers/admin/UserController.php
<?php

namespace App\Http\Controllers\admin;

use App\Helpers\Helper;
use App\Http\Controllers\Controller;
use App\Models\Role;
use App\Src\Actions\admin\Users\{GetUserIndexAction, StoreUserAction, GetUserByIdAction, UpdateUserAction, DeleteUserAction};
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        try {
            $users = (new GetUserIndexAction($request->all()))->execute();
            $roles = Role::all();

            return view('admin.pages.users.index', [
                'users' => $users,
                'roles' => $roles
            ]);
        } catch(\Exception $e) {
            return $e->getMessage();
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.pages.users.create', [
            'roles' => Role::all()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'role' => 'required',
            'name' => 'required|string',
            'email' => 'required|email|unique:users',
            'password' => 'required'
        ]);

        if($validator->fails()) {
            return response()->json([
                'status' => 'failed',
                'type' => 'validate',
                'error' => ucwords(implode(', ', $validator->errors()->all()))
            ]);
        }

        try {
            $user = (new StoreUserAction($request->all()))->execute();

            return Helper::jsonSuccessResponse('User created!', $user);
        } catch(\Exception $e) {
            return Helper::jsonFailedResponse('', $e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = (new GetUserByIdAction(decrypt($id)))->execute();

        return view('admin.pages.users.edit', [
            'user' => $user
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'role' => 'required',
            'name' => 'required|string',
            'email' => 'required|email|unique:users',
        ]);

        if($validator->fails()) {
            return response()->json([
                'status' => 'failed',
                'type' => 'validate',
                'error' => ucwords(implode(', ', $validator->errors()->all()))
            ]);
        }

        try {
            $user = (new UpdateUserAction($request->all(), decrypt($id)))->execute();

            return Helper::jsonSuccessResponse('User updated!', $user);
        } catch(\Exception $e) {
            return Helper::jsonFailedResponse('', $e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $user = (new DeleteUserAction(decrypt($id)))->execute();

            return Helper::jsonSuccessResponse('User deleted!', $user);
        } catch(\Exception $e) {
            return Helper::jsonFailedResponse('', $e->getMessage());
        }
    }
}

resources/views/admin/pages/users/create.blade.php
<div class="container-fluid mt-3" style="max-width: 800px">
    <div class="row">
        <div class="col-lg-12">
            <form action="{{ route('admin.users.store') }}" method="POST" id="user-form">
                @csrf
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        <h3 class="card-label">Create New Admin User</h3>
                    </div>
                </div>
                <div class="card-body">
                    <input type="hidden" name="role" value="1">
                        <div class="basic-form">
                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">Name</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control input-default" name="name" id="name" placeholder="Fill it with Name">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">Email</label>
                                <div class="col-sm-10">
                                    <input type="email" class="form-control input-default" name="email" id="email" placeholder="Fill it with Email">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">Password</label>
                                <div class="col-sm-10">
                                    <input type="password" class="form-control input-default" name="password" id="password" placeholder="Fill it with Password">
                                </div>
                            </div>
                </div>
                <div class="card-footer">
                    <div class="row">
                        <div class="col-md-5" style="float: left">
                            
                        </div>
                        <div class="col-md-7">
                            <div style="float: right">
                                <button type="submit" class="btn btn-success">
                                    <i class="icon-pencil"></i> Save
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            </form>
        </div>
    </div>
</div>
<!-- #/ container -->
<script>
    $(document).ready(function() {
        $('#user-form').on('submit', function(e) {
            e.preventDefault();
            $.ajax({
                url: $(this).attr('action'),
                type: $(this).attr('method'),
                data: $(this).serialize(),
                success: function(response) {
                    if(response.status === 'success') {
                        swal({
                            title: 'Success!',
                            text: response.msg,
                            type: 'success',
                            showConfirmButton: false,
                            timer: 2000
                        }, () => {
                            window.location.reload();
                        })
                    } else {
                        swal({
                            title: response.msg,
                            text: response.error,
                            type: 'error',
                        })
                    }
                }
            })
        })
    })
</script>

resources/views/admin/pages/users/edit.blade.php
<div class="container-fluid mt-3" style="max-width: 800px">
    <div class="row">
        <div class="col-lg-12">
            <form action="{{ route('admin.users.update', encrypt($user->id)) }}" method="POST" id="user-form">
                @csrf
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        <h3 class="card-label">Edit Admin User</h3>
                    </div>
                </div>
                <div class="card-body">
                    <input type="hidden" name="role" value="1">
                        <div class="basic-form">
                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">Name</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control input-default" name="name" value="{{ $user->name }}" id="name" placeholder="Fill it with Name">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">Email</label>
                                <div class="col-sm-10">
                                    <input type="email" class="form-control input-default" name="email" value={{ $user->email }} id="email" placeholder="Fill it with Email">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">Password</label>
                                <div class="col-sm-10">
                                    <input type="password" class="form-control input-default" name="password" id="password" placeholder="Fill it with Password">
                                    <small>If you don't want change the password, just leave the password field blank.</small>
                                </div>
                            </div>
                </div>
                <div class="card-footer">
                    <div class="row">
                        <div class="col-md-5" style="float: left">
                            
                        </div>
                        <div class="col-md-7">
                            <div style="float: right">
                                <button type="submit" class="btn btn-success">
                                    <i class="icon-pencil"></i> Save
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            </form>
        </div>
    </div>
</div>
<!-- #/ container -->
<script>
    $(document).ready(function() {
        $('#user-form').on('submit', function(e) {
            e.preventDefault();
            $.ajax({
                url: $(this).attr('action'),
                type: $(this).attr('method'),
                data: $(this).serialize(),
                success: function(response) {
                    if(response.status === 'success') {
                        swal({
                            title: 'Success!',
                            text: response.msg,
                            type: 'success',
                            showConfirmButton: false,
                            timer: 2000
                        }, () => {
                            window.location.reload();
                        })
                    } else {
                        swal({
                            title: response.msg,
                            text: response.error,
                            type: 'error',
                        })
                    }
                }
            })
        })
    })
</script>

resources/views/admin/pages/users/index.blade.php
@extends('admin.layouts.app')

@section('title', env('APP_NAME') . ' | Users')

@section('content')
<div class="row page-titles mx-0">
    <div class="col p-md-0">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">Dashboard</li>
            <li class="breadcrumb-item active"><a href="{{ route('admin.dashboard') }}">Home</a></li>
        </ol>
    </div>
</div>
<div class="container-fluid mt-3">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        <h3 class="card-label">Users Management</h3>
                    </div>
                </div>
                <div class="card-body">
                    <form action="" method="GET">
                        <div class="form-row">
                            <div class="form-group col-md-3">
                                <label>Role</label>
                                <select name="role_id" class="form-control input-default" id="role_id">
                                    <option value="" {{ ((Request()->role_id == '' or empty(Request()->role_id)) ? 'selected' : '') }} selected>.: All Roles :.</option>
                                    @foreach ($roles as $index => $role)
                                        <option value="{{ $role->id }}" {{ (Request()->role_id == $role->id ? 'selected' : '') }}>{{ $role->role_name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group col-md-3">
                                <label>Search Field</label>
                                <input type="text" class="form-control input-default" name="search" id="search" value="{{ Request()->search }}" placeholder="Search by User's name or email">
                            </div>
                            <div class="form-group col-md-3">
                                <label>&nbsp;</label>
                                <button class="btn btn-primary btn-block" type="submit" href="{{ url()->current() }}?role_id={{ Request()->role_id }}&search={{ Request()->search }}">
                                    <i class="icon-magnifier"></i> Search
                                </button>
                            </div>
                            <div class="form-group col-md-3">
                                <label>&nbsp;</label>
                                <a href="javascript:void(0)" data-href="{{ route('admin.users.create') }}" class="btn btn-success btn-block btnAdd">
                                    <i class="icon-plus"></i> Create User
                                </a>
                            </div>
                        </div>
                    </form>
                    {{-- Table Index Users --}}
                    <div class="table-responsive">
                        <table class="table table-striped table-hover" id="users-table">
                            <thead>
                                <tr>
                                    <td>#</td>
                                    <td>Name</td>
                                    <td>Email</td>
                                    <td>Role</td>
                                    <td>Join At</td>
                                    <td>Action</td>
                                </tr>
                            </thead>
                            <tbody>
                                @if(count($users) > 0)
                                    @foreach($users as $index => $user)
                                        <tr>
                                            <td>{!! ($index+1)+((Request::input('page') != 0 ? (Request::input('page')-1) : Request::input('page'))*1) !!}</td>
                                            <td>{{ $user->name }}</td>
                                            <td>{{ $user->email }}</td>
                                            <td>{{ $user->role->role_name }}</td>
                                            <td>{{ date('d-m-Y', strtotime($user->created_at)) }}</td>
                                            <td>
                                                <a href="javascript:void(0)" class="edit-data" data-href="{{ route('admin.users.edit', encrypt($user->id)) }}" title="Edit User">
                                                    <i class="icon-note text-info"></i>
                                                </a>
                                                <a href="javascript:void(0)" class="delete-data" title="Delete User" data-href="{{ route('admin.users.delete', encrypt($user->id)) }}">
                                                    <i class="icon-trash text-danger"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    @endforeach
                                @else
                                    <tr>
                                        <td colspan="6" style="text-align: center">
                                            <i>Data Not Found</i>
                                        </td>
                                    </tr>
                                @endif
                            </tbody>
                        </table>
                    </div>
                    {{-- End of Table Index Users --}}
                </div>
                <div class="card-footer">
                    <div class="row">
                        <div class="col-md-5" style="float: left">
                            <small>Showing {{ $users->count() }} from {{ $users->total() }} data</small>
                        </div>
                        <div class="col-md-7">
                            <div style="float: right">
                                {!! $users->links() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- #/ container -->
@endsection

{{-- Styles Section --}}
@section('styles')
@endsection

{{-- Scripts Section --}}
@section('scripts')
<script>
    function deleteUser(url)
    {
        $.ajax({
                url: url,
                type: 'DELETE',
                data: {
                    _token: '{{ csrf_token() }}'
                },
                success: function(response) {
                    if(response.status === 'success') {
                        swal({
                            title: 'Success!',
                            text: response.msg,
                            type: 'success',
                            showConfirmButton: false,
                            timer: 2000
                        }, () => {
                            window.location.reload();
                        })
                    } else {
                        swal({
                            title: response.msg,
                            text: response.error,
                            type: 'error',
                        })
                    }
                }
            })
    }

    $(document).ready(function() {
        $('.btnAdd').click(function(e) {
            e.preventDefault()
            swalLoading()
            $.ajax({
                url: $(this).attr('data-href'),
                type: 'GET',
                success: function(response) {
                    swal.close()
                    $.fancybox.open([
                        {
                            src: response,
                            type: 'html'
                        }
                    ])
                }
            })
        })

        $('.edit-data').on('click', function(e) {
            e.preventDefault()
            swalLoading()
            $.ajax({
                url: $(this).attr('data-href'),
                type: 'GET',
                success: function(response) {
                    swal.close()
                    $.fancybox.open([
                        {
                            src: response,
                            type: 'html'
                        }
                    ])
                }
            })
        })

        $('.delete-data').on('click', function(e) {
            e.preventDefault()
            let url = $(this).attr('data-href');
            swal({
                type: 'warning',
                title: 'Are you sure want to delete data?',
                text: 'Once deleted, data cannot be restore',
                showCancelButton: true
            }, (result) => {
                if(result) {
                    deleteUser(url)
                }
            })
        })
    })
</script>
@endsection